### ISSUE TITLE
Organize Pipelines

### ISSUE THREAD

**Issue by sertansenturk** [hedonistrh/TurkishMusicGeneration#10]
Create and organize a first draft of the swimlanes to be used in the board

**Reason**
Swimlanes (pipeline in Zenhub terminology) allow us to track the state of each ticket, communicate the cross-team actions, and be consistent with the progress.

The best practice would be to decide the pipeline order and requirements to move the tickets together. Since it would be difficult to gather everyone before the end of the sprint, and @hedonistrh is currently the only active developer, I should make a short Skype chat with him to make the first draft. Then we can use it for some time and see what to change if needed.

Some things we should discuss are:

- How to reflect the Definition of Done to the swimlane names and their order
- The criteria to consider to move a ticket from one lane to the next

**Outcome**
- The pipelines organized in the board.
- Pipeline documentation entered into the repository wiki.

**Comment by hedonistrh** [comment]
Thanks for the documentation. 🙏 

I have read [wiki entry for Swimlane.](https://github.com/hedonistrh/TurkishMusicGeneration/wiki/Swimlanes) It contains whole details which have been discussed and explains clearly how we manage the whole process via our swim lane organization. Thus, we can close this issue at this point.
