### ISSUE TITLE
Provide Conda Environment

### ISSUE THREAD

**Issue by hedonistrh** [hedonistrh/TurkishMusicGeneration#11]
**Summary:**
Provide Conda environment.

**Reason:**
To get same environment and reproduce results easily.

**Steps:**
- Create new Conda environment.
- Install required packages into this environment.
- Export my active environment to a new file.
Note: Follow [this guide.](https://conda.io/docs/user-guide/tasks/manage-environments.html)

**Outcome:**
We will come up with the conda environment. Also, we can double check result.

**Acceptance Criteria:**
One of the contributor can set up the same environment and reproduce the result by only following my written instructions & conda setup.

**Comment by sertansenturk** [comment]
@hedonistrh Given the spikes you are working on this sprint, it looks this ticket is not relevant anymore. I say, let's keep the pull request open for now, but close this ticket. What do you think?

**Comment by hedonistrh** [comment]
Yes, I agree with you. If we need to create our own model, we can try again _Conda_ or just switch to _Docker_ 💯
