### ISSUE TITLE
Definition of Ready

### ISSUE THREAD

**Issue by sertansenturk** [hedonistrh/TurkishMusicGeneration#12]
Define what we deem as a ticket ready to be worked on.

**Reason**
The team should have a consensus on what the contents and minimum requirements of a ticket before we consider as ready. This solves many communications issues such as understanding the scope of a work, discrepancies in deliverables, amount of time needed to spend on a task.

**Design**
The best practice would be to decide the definition of ready (DOR) together. Since it would be difficult to gather everyone before the end of the sprint, and @hedonistrh is currently the only active developer, I should make a short Skype chat with him to make the first draft. Then we can use it for some time and see what to change, if needed.

Some things we should discuss are:
- The types of tickets we would like to have (Epic, feature, spike etc.)
- The required content(s) for each ticket 
- The metadata required for each ticket (labels, points etc.)
    - Briefly discuss how these metadata should be implemented, when possible.

**Outcome**
- The first draft of DOR entered into the repository wiki as documentation.

**Comment by hedonistrh** [comment]
I have read [wiki entry for DOR.](https://github.com/hedonistrh/TurkishMusicGeneration/wiki/Definition-of-Ready) It contains whole details which have been discussed. At that point we can close this issue, however, we can add some details within the project duration.
