### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by sertansenturk** [hedonistrh/TurkishMusicGeneration#13]
Define what we deem as a done ticket

**Reason**
The team should have a consensus on what criteria to be met for different types of tickets. Similar to DOR, DOD solves many communications issues such as understanding the scope of a work, discrepancies in deliverables, the rigor that should be put to finish a task.

**Design**
The best practice would be to decide the definition of done (DOD) together. Since it would be difficult to gather everyone before the end of the sprint, and @hedonistrh is currently the only active developer, I should make a short Skype chat with him to make the first draft. Then we can use it for some time and see what to change if needed.

Some things we should discuss are:
- The steps each different ticket has to pass through/fulfill to be accepted as Done
    - Has a direct effect on the swimlanes/pipelines used in the board

**Outcome**
- The first draft of DOD entered into the repository wiki as documentation.

**Comment by hedonistrh** [comment]
Thanks for the documentation. 🙏 

I have read [wiki entry for DOD.](https://github.com/hedonistrh/TurkishMusicGeneration/wiki/Definition-of-Done) It contains whole details which have been discussed and explains clearly what we need to say _it is done. Thus, we can close this issue at this point.
