### ISSUE TITLE
Estimations

### ISSUE THREAD

**Issue by sertansenturk** [hedonistrh/TurkishMusicGeneration#14]
**One-line summary**
Determine how we estimate the velocity of the tickets

**Reason**
We need to get a agreement how we measure the difficulty/time needed etc. for a ticket

**Design**
- Set a meeting with with @hedonistrh.
- Explain him different estimation methods (points, t-shirt size etc.). 
- Whichever method is selected, define how we understand different velocities.

**Acceptance Criteria**
The agreed estimation method described as a comment.

**Outcome**
Comment. See above

**Comment by sertansenturk** [comment]
@hedonistrh can you review the comment above?

**Comment by hedonistrh** [comment]
Thanks for the documentation. @sertansenturk  🙏

These points' explanations is the same as what we agreed on our Skype meeting. Thus, we can close this issue at this point.
