### ISSUE TITLE
Review of Open Source Projects

### ISSUE THREAD

**Issue by hedonistrh** [hedonistrh/TurkishMusicGeneration#19]
**One-line summary (optional)**
We will prepare review of open source project which is about Music Generation.

**Reason**
We will use existing architectures-methods for our project if applicable.

**Design**
We will start with our existing literature review and check if their code is available or not. If available, we will also check the paper to understand methods. With these informations, we will create summary for other team members. _(If not available, we can send e-mail to authors.)_

**Acceptance Criteria**
It needs to explain:
- What method is used and details of architecture.
- How they represent their input.
- Are there any pre-trained weights can we directly for transfer learning.
- An overview of the code in terms of reproducibility
   - Does the code include the package versions?
   - Does it come with a requirements/environment/docker file?
   - Does it include scripts/guidelines on preprocessing, training, testing, generation etc.?

**Outcome**
We will have a summary of open source methods and how we manipulate these to use with our data format.

**Comment by hedonistrh** [comment]
I would like to assign 5 point, if it is fine for you. @sertansenturk

**Comment by sertansenturk** [comment]
@hedonistrh is there any work left to do from your side, or are you simply waiting for the reviews. If it's the latter, could you move the ticket to "Under review"?

**Comment by hedonistrh** [comment]
I was planning to add more metrics. But, I think those metrics will be enough at that point. So that, I move the ticket to _Under Review_ :) @sertansenturk

**Comment by sertansenturk** [comment]
I merged the pull request. You may close this ticket...
