### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by hedonistrh** [hedonistrh/TurkishMusicGeneration#20]
**One-line summary**
Create a summary for evaluation metrics.

**Reason**
We need to understand our networks can or can not capture-imitate the style of Turkish Music.

**Design**
We already discussed some metrics at our first meeting. _(I will add them as a comment in this issue)_

- We will start with existing works to understand what they use to evaluate their generation. But, they are related with mostly western musics. So that, we also need some specific metrics for Turkish Music. (Some specific discriminator for makam, usul etc.) 
- We will check open source libraries like mir-eval etc. 
- The Folk RNN paper and @sertansenturk's master thesis can be helpful for us.

**Acceptance Criteria**
- Each of them should related with symbolic representation. (one-hot, piano-roll etc.)
- Each of metrics should be explained in a paragraph.
- If there is open source implementation of it, please indicate that. 

**Outcome**
We will have a list of evaluation metrics and their summaries.

**Comment by hedonistrh** [comment]
Some candidates for evaluation metrics:
- Note distribution
- A song’s length
- Long term structure (for instance AABA)
- A note-to-note transition
- Perplexity/Cross Entropy
- Makam Classification
- Usul Classification
 - User studies
- Note Distribution of the first section, second section etc.

**Comment by sertansenturk** [comment]
How many points is this ticket?

**Comment by hedonistrh** [comment]
Sorry for my mistake. :) I would like to assign 5 point, if it is fine for you.

**Comment by hedonistrh** [comment]
[This paper](http://www.musicinformatics.gatech.edu/wp-content_nondefault/uploads/2018/11/postprint.pdf) can be helpful. I will investigate it.

**Comment by sertansenturk** [comment]
@hedonistrh is there any work left to do from your side, or are you simply waiting for the reviews. If it's the latter, could you move the ticket to "Under review"?

**Comment by hedonistrh** [comment]
I was planning to add more metrics. But, I think those metrics will be enough at that point. So that, I move the ticket to _Under Review_ :) @sertansenturk

**Comment by hedonistrh** [comment]
Now, we have our [evaluation metrics.](https://github.com/hedonistrh/TurkishMusicGeneration/blob/master/review-evaluation-metrics.md) We will decide which ones are focused on at the next meeting.
