### ISSUE TITLE
Decide the makam and usuls in the dataset

### ISSUE THREAD

**Issue by sertansenturk** [hedonistrh/TurkishMusicGeneration#21]
**Reason**
We have to decide which makams & usuls to include in the dataset so that we can have a focused but representative dataset.

**Design**
In the latest version of the SymbTr dataset.
- Read the score names, which are in the form makam--form--usul--name--composer
   - Extract the makam and usul from the score name
   - List the 20 most common makams
   - Select the scores in these makams and list the most common usuls
- Group the usuls by "zaman" (number of strokes per usul cycle) and get the counts of top zaman groups

**Acceptance Criteria**
The makam and usuls are decided

**Outcome**
- The counts of top makams and usuls
- The counts of top zamans in the scores filtered by top makams

**Comment by sertansenturk** [comment]
The number of scores in top makams are:

| makam | count|
|---|---|
| hicaz | 157 |
| nihavent | 130 |
| ussak | 118 |
| rast | 109 |
| huzzam | 97 |
| huseyni | 92 |
| segah | 92 |
| mahur | 88 |
| hicazkar | 79 |
| kurdilihicazkar | 70 |
| muhayyer | 67 |
| saba | 66 |
| acemasiran | 63 |
| beyati | 62 |
| buselik | 57 |
| karcigar | 53 |
| ~hicaz_humayun~ | ~38~ |
| ~acemkurdi~ | ~37~ |
| ~evic~ | ~33~ |
| ~muhayyerkurdi~ | ~32~ |

Top 10 makams have more than 1000 music scores.

The top usuls in the scores of the top 16 makams are:

| usul | count | beats |
| ---- | ----- |
| aksak | 163 | 9 |
| duyek | 145 | 8 |
| sofyan | 126 | 4 |
| curcuna | 66 | 10 |
| agiraksak | 53 | 9 |
| nimsofyan | 59 | 2 |
| semai | 53 | 3 |
| aksaksemai | 35 | 10 |
| senginsemai | 37 | 6 |
| turkaksagi | 35 | 5 |
| devrihindi | 27 | 7 |
| yuruksemai | 26 | 6 |
| kapali_curcuna | 22 | 10 |
| yuruksemai_ii | 20 | 6 |
| musemmen | 17 | 8 |
| devrikebir | 12 | 28 |
| raksaksagi | 10 | 9 |
| agirduyek | 8 | 8 |

If we pick the top 4 usuls & top 10 makams we will have 500 scores (12.5 scores per pair on average).

To increase the data, we may group the usuls by zaman (the number of "beats" per cycle) and pick the top. I roughly annotated the zamans of each usul (please correct me if I have made a mistake). The number of scores per group is below:

| zaman | count | 
| ---- | ----- |
| 9 | 216 |
| 8 | 162 |
| 4 | 126 |
| 10 | 123 |
| 6 | 83 |
| 2 | 59 |
| 3 | 53 |
| 5 | 35 |
| 7 | 27 |

If we pick the top 4 zamans & top 10 makams we will have 627 scores (15.675 scores per pair on average).

**Comment by barisbozkurt** [comment]
Thanks Sertan. I suggest use of top 8 makams, kurdilihicazkar is a compound makam which will create lots of confusions. The folowing makams are related/close in the top 8: uşşak-hüseyni, rast-mahur,  hüzzam-segah. 

I agree with the use of top 4 usuls.

**Comment by sertansenturk** [comment]
Thank you Baris. You might have received a scheduled e-mail a few minutes ago, which was asking the questions you have answered above. Please ignore the e-mail.

 I'll start preparing the dataset in the evening.

**Comment by sertansenturk** [comment]
There are 451 scores in total. Below are the makam/usul/form counts:

| | count |
| - | - |
| hicaz | 78 |
| nihavent | 64 |
| ussak | 61 |
| huzzam | 53 |
| mahur | 51 |
| rast | 51 |
| huseyni | 48 |
| segah | 45 |

| | count |
| - | - |
| aksak | 139 |
| duyek | 124 |
| sofyan | 114 |
| curcuna | 59 |
| kapali_curcuna | 15 |

I have also added the scores in kapali_curcuna, which is - as far as I know - another variant of curcuna Kemal Karaosmanoglu has annotated.

| | count |
| - | - |
| sarki | 274 |
| turku | 82 |
| seyir | 15 |
| ilahi | 11 |
| ornek_oz | 10 |
| fantezi | 9 |
| aranagme | 8 |
| rumeliturkusu | 5 |
| kupe | 4 |
| mars | 4 |
| kanto | 3 |
| etud | 3 |
| tavsanca | 3 |
| popsarkisi | 2 |
| beste | 1 |
| mersiye | 1 |
| ninni | 1 |
| kasaphavasi | 1 |
| kalenderi | 1 |
| sugul | 1 |
| salatuselam | 1 |
| nefes | 1 |
| kurthavasi | 1 |
| pesrev | 1 |
| kocekce | 1 |
| sazeseri | 1 |
| oyunhavasi | 1 |
| divan | 1 |
| nakis | 1 |
| cocuksarkisi | 1 |
| karsilama | 1 |
| zeybek | 1 |

@barisbozkurt are there any forms, we should take out?

**Comment by barisbozkurt** [comment]
'Form' side of the story is complex, the choice will be very much target and model dependent. For the moment, let's start by incşuding everything

**Comment by sertansenturk** [comment]
Thank you for the clarifications. I'm closing this issue and continue with #23 in the evening.
