### ISSUE TITLE
Music21-Midi Manipulation

### ISSUE THREAD

**Issue by hedonistrh** [hedonistrh/TurkishMusicGeneration#29]
**One-line summary (optional)**
Try to manipulate our midi via Music21 to get rid of polyphony.

**Reason**
MagentaRNN gives exception for some of our datas.

**Design**
- Read the midi files via Music21
- Try to manipulate some part like delete etc. to get monophonic sequences
- Create new .midi file

**Acceptance Criteria**
- MelodyRNN should work with it. 

**Outcome**
- Script for convert polyphonic midis into monophonic midis.

**Comment by sertansenturk** [comment]
I think this should be a spike ticket rather than a feature: you still don't know if it's possible.

Once (and if) it's feasible then you should open another ticket to build the feature, which manipulate the scores. Could you edit the ticket accordingly with the correct spike DOR?

**Comment by hedonistrh** [comment]
According to [our experiment](https://github.com/hedonistrh/TurkishMusicGeneration/issues/26#issuecomment-468449823), manipulation will not be helpful. Lets close this issue. @sertansenturk @magdalenafuentes
